# Width and Height of the project window
WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 616

# Character's location
CHARACTER_HEIGHT = 150
CHARACTER_WIDTH = 150
CHARACTER_X_POS = 30
CHARACTER_Y_POS = 310

# Character's paths


# Ground
GROUND_COLOR = (192, 192, 192)
GROUND_Y = 450
GROUND_X = 0
GROUND_HEIGHT = 166
GROUND_WIDTH = WINDOW_WIDTH

#jump
JUMP_COUNT = 10

#pause button
PAUSE_X_POS = 1000
PAUSE_Y_POS = -10
PAUSE_WIDTH = 100
PAUSE_HEIGHT = 100

#score
SCORE_X_POS = 15
SCORE_Y_POS = 40
SCORE_SIZE = 20
SCORE_COLOR = (255, 255, 255)

#Hearts
HEART_X_POS_1 = 10
HEART_X_POS_2 = 45
HEART_X_POS_3 = 80
HEART_Y_POS = 10
HEART_WIDTH = 30
HEART_HEIGHT = 30
HEART_PATH = "images/objects/Heart.png"
HEART_ID = "HEART"


# Railing
RAILING_TYPE = "railing"
RAILING_WIDTH = 400
RAILING_HEIGHT = 300
RAILING_START_X = WINDOW_WIDTH + RAILING_WIDTH
RAILING_Y = 195
RAILING_IMAGE = "images/obsticles/Railing.png"

# Stairs
STAIRS_TYPE = "stairs"
STAIRS_WIDTH = 100
STAIRS_HEIGHT = 100
STAIRS_START_X = WINDOW_WIDTH + STAIRS_WIDTH
STAIRS_Y = 350
STAIRS_IMAGE =  "images/obsticles/Stairs.png"

# Bird
BIRD_TYPE = "bird"
BIRD_WIDTH = 75
BIRD_HEIGHT = 75
BIRD_START_X = WINDOW_WIDTH + BIRD_WIDTH
BIRD_Y = 295
BIRD_IMAGE =  "images/obsticles/Bird.png"