# Data
BEST_SCORE = "best_score"
START_HEARTS = 3
ERROR_COLOR = (255, 0, 0)
SUCCESS_COLOR = (76, 153, 0)

# Coin value
DEFAULT_COIN_VALUE = 1
BIG_COIN_VALUE = 50

# COLORS
RED = (255, 0, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)

# Width and Height of the project window
WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 616

# Character's location
CHARACTER_HEIGHT = 150
CHARACTER_WIDTH = 150
CHARACTER_X_POS = 30
CHARACTER_Y_POS = 310

# Characters
CHARACTERS_AMOUNT = 5
CHARACTER_EQUIPPED = "equipped"
CHARACTER_OWN = "yes"
CHARACTER_NOT_OWN = "no"
CHARACTER_PATH = "images/Characters/"

# Coins homepage
COIN_TEXT_X = WINDOW_WIDTH-70
COIN_IMAGE_X = WINDOW_WIDTH-110
COIN_Y = 20
COIN_SIZE = 30
COIN_COLOR = (255, 255, 255)
COIN_WIDTH = 35
COIN_HEIGHT = 35
COIN_PATH = "images/Objects/Coin.png"

# SkateGame logo
LOGO_TEXT_X = 110
LOGO_IMAGE_X = 68
LOGO_Y = 20
LOGO_SIZE = 30
LOGO_COLOR = (255, 255, 255)
LOGO_WIDTH = 35
LOGO_HEIGHT = 35
LOGO_PATH = "images/Objects/Skate.png"


# Play button
PLAY_PATH = "images/buttons/Play.png"
PLAY_WIDTH = 290
PLAY_HEIGHT = 230
PLAY_X = 25
PLAY_Y = 150
PLAY_ID = "PLAY"

# Shop button
SHOP_PATH = "images/buttons/Shop.png"
SHOP_WIDTH = 100
SHOP_HEIGHT = 70
SHOP_X = 76
SHOP_Y = 400
SHOP_ID = "SHOP"

# Home button
HOME_X = WINDOW_WIDTH-70
HOME_Y = 20
HOME_WIDTH = 50
HOME_HEIGHT = 50
HOME_PATH = "images/buttons/Home.png"
HOME_ID = "HOME"

# Shop positions
SHOP_CHARACTER_HEIGHT = 150
SHOP_CHARACTER_WIDTH = 150
SHOP_CHARACTER_X_POS_1 = 50
SHOP_CHARACTER_X_POS_2 = 250
SHOP_CHARACTER_X_POS_3 = 450
SHOP_CHARACTER_X_POS_4 = 650
SHOP_CHARACTER_X_POS_5 = 850
SHOP_CHARACTER_Y_POS = 310
SHOP_PRICE_Y_POS = 465
SHOP_PRICE_SIZE = 20
SHOP_COLOR = (255, 255, 255)
STATUS_COLOR = (0, 0, 255)

# Shop message
SHOP_MESSAGE_Y = 520
SHOP_MESSAGE_X = WINDOW_WIDTH/2-200
SHOP_MESSAGE_SIZE = 25

# Arrow
ARROW_Y_POS = 210
ARROW_PATH = "images/Objects/Arrow.png"
ARROW_WIDTH = 50
ARROW_HEIGHT = 70
ARROW_X = -100

# Shop prices
PRICES = [None, 0, 5000, 7500, 10000, 12000]
CHARACTER_PRICE_1 = 0
CHARACTER_PRICE_2 = 5000
CHARACTER_PRICE_3 = 7500
CHARACTER_PRICE_4 = 10000
CHARACTER_PRICE_5 = 12000

# Background
BACKGROUND_PATH = "images/backgrounds/background.png"

# Ground
GROUND_COLOR = (192, 192, 192)
GROUND_Y = 450
GROUND_X = 0
GROUND_HEIGHT = 166
GROUND_WIDTH = WINDOW_WIDTH

# jump
JUMP_COUNT = 10

# pause button
PAUSE_X_POS = 1000
PAUSE_Y_POS = -10
PAUSE_WIDTH = 100
PAUSE_HEIGHT = 100
PAUSE_PATH = "images/buttons/Pause.png"
PAUSE_ID = "PAUSE"

# score
SCORE_X_POS = 15
SCORE_Y_POS = 40
SCORE_SIZE = 20
SCORE_COLOR = (255, 255, 255)

# Game coins
COIN_GAME_TEXT_X = 50
COIN_GAME_IMAGE_X = 10
COIN_GAME_Y = 60
COIN_GAME_SIZE = 30
COIN_GAME_COLOR = (255, 255, 255)



# Hearts
HEART_X_POS_1 = 10
HEART_X_POS_2 = 45
HEART_X_POS_3 = 80
HEART_X_OUT = -50
HEART_Y_POS = 10
HEART_WIDTH = 30
HEART_HEIGHT = 30
HEART_PATH = "images/objects/Heart.png"
HEART_ID = "HEART"

# Best score message
BEST_SCORE_MESSAGE_X = 380
BEST_SCORE_MESSAGE_Y = 200
BEST_SCORE_MESSAGE_SIZE = 50

# Best score homepage
BEST_SCORE_TEXT_X = WINDOW_WIDTH-70
BEST_SCORE_Y = 70
BEST_SCORE_SIZE = 30
BEST_SCORE_COLOR = (255, 255, 255)
TROPHY_IMAGE_X = WINDOW_WIDTH-108
TROPHY_WIDTH = 33
TROPHY_HEIGHT = 33
TROPHY_PATH = "images/Objects/Trophy.png"

# Railing
RAILING_TYPE = "award"
RAILING_WIDTH = 400
RAILING_HEIGHT = 300
RAILING_START_X = WINDOW_WIDTH + RAILING_WIDTH
RAILING_Y = 198
RAILING_IMAGE = "images/obsticles/Railing.png"

# Stairs
STAIRS_TYPE = "stairs"
STAIRS_WIDTH = 100
STAIRS_HEIGHT = 100
STAIRS_START_X = WINDOW_WIDTH + STAIRS_WIDTH
STAIRS_Y = 350
STAIRS_IMAGE = "images/obsticles/Stairs.png"

# Bird
BIRD_TYPE = "bird"
BIRD_WIDTH = 160
BIRD_HEIGHT = 160
BIRD_START_X = WINDOW_WIDTH + BIRD_WIDTH
BIRD_Y = 200
BIRD_IMAGE = "images/obsticles/Bird.png"

# Clouds
CLOUD_WIDTH = 200
CLOUD_HEIGHT = 100
CLOUD_Y = [0, 20, 10, 25, -10, 5]
CLOUD_X = [WINDOW_WIDTH, WINDOW_WIDTH+200, WINDOW_WIDTH+400, WINDOW_WIDTH+600, WINDOW_WIDTH+800, WINDOW_WIDTH+1000]
CLOUD_IMAGE = "images/Objects/Cloud.png"

# Resume button
RESUME_PATH = "images/buttons/Resume.png"
RESUME_WIDTH = 150
RESUME_HEIGHT = 150
RESUME_X = WINDOW_WIDTH/2 - 230
RESUME_Y = 350
RESUME_ID = "RESUME"

# Quit button
QUIT_PATH = "images/buttons/Quit.png"
QUIT_WIDTH = 250
QUIT_HEIGHT = 250
QUIT_X = WINDOW_WIDTH/2 - 30
QUIT_Y = 300
QUIT_ID = "QUIT"

# Game Paused image
PAUSED_IMAGE_PATH = "images/GameSituation/GamePaused.png"
PAUSED_IMAGE_WIDTH = 300
PAUSED_IMAGE_HEIGHT = 300
PAUSED_IMAGE_X = WINDOW_WIDTH/2 - 170
PAUSED_IMAGE_Y = 120
PAUSED_IMAGE_ID = "GAME_PAUSED"

# Game over image
OVER_PATH = "images/GameSituation/GameOver.png"
OVER_WIDTH = 500
OVER_HEIGHT = 250
OVER_X = WINDOW_WIDTH/2 - 250
OVER_Y = 140
OVER_ID = "GAME_OVER"

# Game over score
OVER_SCORE_X_POS = WINDOW_WIDTH/2 - 100
OVER_SCORE_Y_POS = 370
OVER_SCORE_SIZE = 50
OVER_SCORE_COLOR = (255, 255, 255)

# HEART AWARD
HEART_AWARD_TYPE = "heart"
HEART_AWARD_WIDTH = 50
HEART_AWARD_HEIGHT = 50
HEART_AWARD_START_X = WINDOW_WIDTH + HEART_AWARD_WIDTH
HEART_AWARD_Y = 200
HEART_AWARD_IMAGE = "images/Objects/Heart.png"

# COIN AWARD
COIN_AWARD_TYPE = "coin"
COIN_AWARD_WIDTH = 50
COIN_AWARD_HEIGHT = 50
COIN_AWARD_START_X = WINDOW_WIDTH + COIN_AWARD_WIDTH
COIN_AWARD_Y = 200
COIN_AWARD_IMAGE = "images/Objects/Coin.png"







